name: "うぇぶかのーと"
short_name: "うぇぶかのーと"
description: "第66回チーフが翠巒祭総務班Web課について色々書き連ねます。"
author: "Chiefs of web partment"
url:
  path: "/note.suiranfes.com"
  host: "suiranfes.github.io"
  scheme: https
pages_src:
  path: "./pages/"
  src: "**/*.{html,htm,pug,md}"
language: ja
page_namingrule: name
theme_color:
  primary: "#ffffff"
  secondary: "#000000"
default:
  template: default
social_media:
  twitter:
    stalk: suiranfes
    share: true
    card: true
  LINE:
    stalk: false
    share: true
  facebook:
    stalk: false
    share: true
  flickr:
    stalk: false
    share: false
  github:
    stalk: suiranfes
    share: false
  share_button: true
rss: false
disqus: false
ga: false
sidebar: true
manifest:
  start_url: "/"
  display: standalone
meta_pages: ['404', 'offline']
sw: "js|css|png|jpeg|jpg|svg|svgz|woff2"